### ISSUE TITLE
Reject tasks for which the function will not be resolved

### ISSUE THREAD

**Issue by dspasojevic** [agiledigital-labs/aws-durable-lambda#104]

**Comment by NoxHarmonium** [comment]
To clarify, does this mean rejecting a task that times out?

**Comment by dspasojevic** [comment]
This is probably less relevant if we turn the plugin inside out.

Right now, you can submit a task for a function that does not exist. It can never succeed because there is nothing to be invoked by the orchestrator. Better to fail that sort of stuff upfront to give a developer (I guess also an attacker 🤔) good feedback.

Happy to close this as unnecessary given #107 is the preferred structure.
