### ISSUE TITLE
Billing issues blocking builds

### ISSUE THREAD

**Issue by NoxHarmonium** [agiledigital-labs/aws-durable-lambda#48]
After merging the last PR and updating the renovate settings, it seems like we have run out of Github Actions credits for the agiledigital-labs account.

For example:

> [package (serverless-jetpack, ubuntu-latest)](https://github.com/agiledigital-labs/aws-durable-lambda/runs/7247266275?check_suite_focus=true)
The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.

I'm not sure whether we can get more credits in this organisation, or if I need to set up a builder somewhere.

**Comment by dspasojevic** [comment]
Repo is now public. Build minutes are free.
